title: Grand Opening
author: SYCPI
email: sam@icpmass.com
description: > # this means to ignore newlines until "baseurl:"
  A little description of what is to come!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
